// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrZgMzBMGtM-KL986-Xc8twey3wuR1vhc',
    appId: '1:697207981464:web:362568e7983f74dd6e97ed',
    messagingSenderId: '697207981464',
    projectId: 'post-4ec83',
    authDomain: 'post-4ec83.firebaseapp.com',
    storageBucket: 'post-4ec83.appspot.com',
    measurementId: 'G-GEJ16PHS37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDygNrvtWNmp1o9oJN8RQ1Y71c9LpO9KOg',
    appId: '1:697207981464:android:e24658d8356136436e97ed',
    messagingSenderId: '697207981464',
    projectId: 'post-4ec83',
    storageBucket: 'post-4ec83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhVLwrkLUnTuNXoGzxR9q0DSZ9c5fZ3NI',
    appId: '1:697207981464:ios:09c998d5dcfa24bc6e97ed',
    messagingSenderId: '697207981464',
    projectId: 'post-4ec83',
    storageBucket: 'post-4ec83.appspot.com',
    iosClientId: '697207981464-uqu7545gjfkfs4a8edioj8sghlnhgd09.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogPost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhVLwrkLUnTuNXoGzxR9q0DSZ9c5fZ3NI',
    appId: '1:697207981464:ios:09c998d5dcfa24bc6e97ed',
    messagingSenderId: '697207981464',
    projectId: 'post-4ec83',
    storageBucket: 'post-4ec83.appspot.com',
    iosClientId: '697207981464-uqu7545gjfkfs4a8edioj8sghlnhgd09.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogPost',
  );
}
